# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: myvars

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |

    git clone https://$(AZURE_DEVOPS_PAT)@dev.azure.com/rajapriya14/SampleProj/_git/RpRepo RpRepo
    cd RpRepo
    git remote add github https://$(GITHUB_TOKEN)@github.com/rajapriya7/TempMigration 
    git pull origin main --rebase
    git reset --hard origin/main
    git push -u github main 
  displayName: ‘Copy Code to GitHub’

