# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: myvars

steps:
#  - script: |

#       git clone https://$(AZURE_DEVOPS_PAT)@dev.azure.com/rajapriya14/SampleProj/_git/RpRepo RpRepos
#       cd RpRepos
#       git remote add github https://$(GITHUB_PAT)@github.com/rajapriya7/TempMigration 
#       git pull origin main --rebase
#       git reset --hard origin/main
#       git push -u github main 
#    displayName: ‘Copy Code to GitHub’
# - checkout: self
 - script: |
     git clone https://$(AZURE_DEVOPS_PAT)$(cat source_repo) mydir
     cd mydir
     git remote add github https://$(GITHUB_PAT)$(cat destination_repo)
     git pull origin main --rebase
     git pull github origin main --rebase
     git reset --hard origin/main
     git push -u github main
   displayName: ‘Copy Code to GitHub’